In [ ]:
from sklearn import decomposition
import numpy as np

In [ ]:
A = np.array([[1, 1, 1],
              [2, 1, 3],
              [1, 2, 2],
              [3, 1, 2]])

In [ ]:
decomposition.PCA(n_components=2).fit_transform(A)

array([[ 1.08554069,  0.61237244],
       [-0.78241346, -0.61237244],
       [ 0.78241346, -0.61237244],
       [-1.08554069,  0.61237244]])

In [ ]:
A_Centered = A - A.mean(axis=0)

In [ ]:
A.mean(axis=0)

array([1.75, 1.25, 2.  ])

In [ ]:
A_Centered

array([[-0.75, -0.25, -1.  ],
       [ 0.25, -0.25,  1.  ],
       [-0.75,  0.75,  0.  ],
       [ 1.25, -0.25,  0.  ]])

In [ ]:
U, S, Vt = np.linalg.svd(A_Centered)

In [ ]:
U[:, 0:2]

array([[-0.57363485,  0.5       ],
       [ 0.41345261, -0.5       ],
       [-0.41345261, -0.5       ],
       [ 0.57363485,  0.5       ]])

In [ ]:
Sigma = np.zeros((2, 2), dtype=float)
Sigma[:2, :2] = np.diag(S[:2])

In [ ]:
U[:, 0:2] @ Sigma

array([[-1.08554069,  0.61237244],
       [ 0.78241346, -0.61237244],
       [-0.78241346, -0.61237244],
       [ 1.08554069,  0.61237244]])